export const todayDeals = [
  {
    img: "https://m.media-amazon.com/images/I/41xnfQ6+TCL._AC_SY200_.jpg",
    discount: "38",
    DealOfDay: "Deal of the day",
    desc: "Best selling Vivo smartphones",
  },
  {
    img: "https://m.media-amazon.com/images/I/81TBkVDGeGL._AC_SY200_.jpg",
    discount: "46",
    DealOfDay: "Deal of the day",
    desc: "Men's Footwear: Bata, Hush Puppies and more",
  },
  {
    img: "https://m.media-amazon.com/images/I/41bLD50sZSL._AC_SY200_.jpg",
    discount: "21",
    DealOfDay: "Deal of the day",
    desc: "iQOO Z7s",
  },
  {
    img: "https://m.media-amazon.com/images/I/81VQYbV0-wL._AC_SY200_.jpg",
    discount: "37",
    DealOfDay: "Deal of the day",
    desc: "Women's Footwear: Bata, Hush Puppies and more",
  },
  {
    img: "https://m.media-amazon.com/images/I/51kdwtY1KvL._AC_SY200_.jpg",
    discount: "87",
    DealOfDay: "Deal of the day",
    desc: "Wallpapers from wolpin",
  },
  {
    img: "https://m.media-amazon.com/images/I/41uGjvXbeBL._AC_SY200_.jpg",
    discount: "95",
    DealOfDay: "Deal of the day",
    desc: "Best offers o PC and Electronic accessories",
  },
  {
    img: "https://m.media-amazon.com/images/I/41dA113N-LL._AC_SY200_.jpg",
    discount: "67",
    DealOfDay: "Deal of the day",
    desc: "Best Offers on PUMA Footwear",
  },
  {
    img: "https://m.media-amazon.com/images/I/41dA113N-LL._AC_SY200_.jpg",
    discount: "65",
    DealOfDay: "Deal of the day",
    desc: "Best Offers on PUMA Footwear",
  },
  {
    img: "https://m.media-amazon.com/images/I/31i8GB3mD2L._AC_SY200_.jpg",
    discount: "37",
    DealOfDay: "Deal of the day",
    desc: "WaterScience best deals Bath Faucets and more",
  },
  {
    img: "https://m.media-amazon.com/images/I/41sx753+kXL._AC_SY200_.jpg",
    discount: "74",
    DealOfDay: "Deal of the day",
    desc: "Lowest prices on Smart Bulbs",
  },
  {
    img: "https://m.media-amazon.com/images/I/31Ri-FAMBUL._AC_SY200_.jpg",
    discount: "4",
    DealOfDay: "Deal of the day",
    desc: "Apple Airpods starting Rs. 12499",
  },
  {
    img: "https://m.media-amazon.com/images/I/31+JUVeDCmL._AC_SY200_.jpg",
    discount: "4",
    DealOfDay: "Deal of the day",
    desc: "Deals on Layasa",
  },
  {
    img: "https://m.media-amazon.com/images/I/516WPi2+IYL._AC_SY200_.jpg",
    discount: "50",
    DealOfDay: "Deal of the day",
    desc: "Premium Handbags: Da Milano",
  },
  {
    img: "https://m.media-amazon.com/images/I/41OqTpLJnWL._AC_SY200_.jpg",
    discount: "65",
    DealOfDay: "Deal of the day",
    desc: "Starting 299 - ASIAN Footwear Collection",
  },
  {
    img: "https://m.media-amazon.com/images/I/41gMugnZ6lL._AC_SY200_.jpg",
    discount: "82",
    DealOfDay: "Deal of the day",
    desc: "Daily Objects wireless and more",
  },
  {
    img: "https://m.media-amazon.com/images/I/310L1tvautL._AC_SY200_.jpg",
    discount: "50",
    DealOfDay: "Deal of the day",
    desc: "Ortho Slippers & Flip Flops",
  },
  {
    img: "https://m.media-amazon.com/images/I/51MTW5OKkUS._AC_SY200_.jpg",
    discount: "87",
    DealOfDay: "Deal of the day",
    desc: "Wallpapers from wolpin",
  },
  {
    img: "https://m.media-amazon.com/images/I/41pyFK774YL._AC_SY200_.jpg",
    discount: "72",
    DealOfDay: "Deal of the day",
    desc: "GRIVAN, LivesUp Bath & Kitchen accessories",
  },
];
